### ISSUE TITLE
Defocusing init code after editing re-runs previous version of init, not the most recent edits

### ISSUE THREAD

**Issue by acedrew** [ACE-IoT-Solutions/ace-svg-react#18]
When leaving the init code edit window, the code that was present the last time the editor was defocused is ran, not the most recent.

**Comment by acedrew** [comment]
@evannorton if there isn't an obvious solution for this, a button that triggers a complete re-init is a requested feature that would be a better workaround than what we have.

**Comment by evannorton** [comment]
![image](https://user-images.githubusercontent.com/35230033/130135896-8c078545-eddd-441d-8f8f-ba981b935d76.png)
The problem was that on line 212 you set this.state.initFunction to the new value, but on 223 you reference the old state in state of this new value. About to put in a simple PR to fix this.
