### ISSUE TITLE
Grafana version 8 and ace-svg plugin does not play well

### ISSUE THREAD

**Issue by ilayn** [ACE-IoT-Solutions/ace-svg-react#21]
Super thanks for this plugin which makes life extremely easy. We recently upgraded to Grafana 8 but it seems like there is some problems.

I didn't know how to start troubleshooting since the plugin never kicks in so I'm just giving a heads up about it.

**Comment by tobehn** [comment]
I just updated to Grafana 8.
The Plug-in is not loading anymore.
Instead it says _Panel plugin not found: aceiot-svg-panel_ in the Panel.

Is this plugin compatible to Grafana 8 ?
If not? What needs to be done and is there anything I can help with?

**Comment by tobehn** [comment]
The Plugin is unsigned:
https://grafana.com/docs/grafana/latest/plugins/plugin-signatures/

Perhaps this ace-svg-react can be submitted for signing:
https://grafana.com/docs/grafana/latest/developers/plugins/sign-a-plugin/

Meanwhile it can be allowed to load on startup by setting it in _allow_loading_unsigned_plugin_ in grafana.ini:
https://grafana.com/docs/grafana/latest/administration/configuration/#allow_loading_unsigned_plugins

**Comment by acedrew** [comment]
The latest version was meant to be signed, we'll take a look and get this
resolved.

Thanks for the heads up.

**Comment by tobehn** [comment]
I am very sorry. I missed to update the plugin itself. Now i have the latest version and it states _signed_ under plugins.

In the end i realized i had that problem due to an old version of the plugin (0.0.6) which might have not been install via _grafana-cli_. So i had both versions (0.0.6 and 0.0.10) in my plugins folder. Even though it stated _signed_ in _grafana plugins_ it seemed to load the older version of the plugin.
After manually removing the old version and reinstalling the newest via CLI the loading problem was gone. Also if removed removed it from _allow_loading_unsigned_plugins_.

**Comment by ilayn** [comment]
I can also confirm that we have a working instance of the plugin. I don't know the exact reason but our DevOps reinstantiated the plugins and things went back to normal. Sorry for the noise.

**Comment by colramos-amd** [comment]
@tobehn was your issue a problem of "Modified signature"?

I encountered a similar issue today and was wondering if the problems are related. Mine's listed as #22

**Comment by tobehn** [comment]
> was your issue a problem of a "Modified signature"?

no, the plugin was marked "unsigned"
in my case it happend due to a second instance of the plugin, that somehow made it into my plugin folder. When i installed the plugin via grafana-cli i got the latest published version. By having the two versions in the plugin folder grafana seemed to load the older version. At least the unsigned label was gone after i deleted the old version.
