### ISSUE TITLE
Modified Signiture: Not shown in Grafana

### ISSUE THREAD

**Issue by colramos-amd** [ACE-IoT-Solutions/ace-svg-react#22]
I downloaded a .zip of main branch to run on my own machine on 8/03. Grafana complains that the signature has been modified and is refusing to show the plugin.

![Screenshot from 2021-08-03 16-34-10](https://user-images.githubusercontent.com/87152878/128099411-efc6fb82-fcfa-4b25-804b-8ee67a1e3de0.png)

As noted in the Grafana docs...

> allow_loading_unsigned_plugins:
> 
> Enter a comma-separated list of plugin identifiers to identify plugins to load even if they are unsigned. Plugins with modified signatures are never loaded.
> 
> We do not recommend using this option. For more information, refer to Plugin signatures.

I'm 99% sure this wasn't an issue with my installation. I made sure it's in my Grafana plugins folder, yarn install/dev ran without any problems, and the proj ID is listed in my grafana.ini `allow_loading_unsigned_plugins`

**Comment by acedrew** [comment]
@colramos-amd Do you have other plugins installed from local source that are working correctly? If you are allowing unsigned from local, I would start with deleting the MANIFEST.txt from the dist folder. I think you might want to file this as an issue in the grafana repository as well, because it sounds like when grafana detects a plugin that has signing information, it attempts to verify it, despite it being in the allow unsigned list.

**Comment by acedrew** [comment]
@colramos-amd any updates on this? Will close, as no one else seems to be having this issue.
